(ns conduit.require
  (:use [conduit.core :exclude [disperse test-conduit test-conduit-fn]])
  (:refer-clojure :exclude [case comp juxt reductions filter map identity]))

(def identity pass-through)
(def proc a-arr)
(def case a-selectp)
(def comp a-comp)
(def split a-all)
(def juxt a-par)
(def reductions a-loop)
(def map conduit-map)
(def filter a-filter)
(def select a-select)
(def selectp a-selectp)
(def if a-if)
(def try a-catch)
(def finally a-finally)
(def disperse conduit.core/disperse)
(def test-conduit conduit.core/test-conduit)
(def test-conduit-fn conduit.core/test-conduit-fn)
(defmacro def [name args & body]
  `(def ~name (a-arr (fn ~name ~args ~@body))))
